/** v0.8 standard catalog component keys — keep in sync with backend `a2ui_v08_catalog.py`. */
export const V08_STANDARD_CATALOG_COMPONENTS = new Set<string>([
  'Text',
  'Image',
  'Icon',
  'Video',
  'AudioPlayer',
  'Row',
  'Column',
  'List',
  'Card',
  'Tabs',
  'Divider',
  'Modal',
  'Button',
  'CheckBox',
  'TextField',
  'DateTimeInput',
  'MultipleChoice',
  'Slider',
])
